/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginPackage;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

/**
 *
 * @author nidul
 */
public class forgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form loginInterface
     */
    public forgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jpanelLeft = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jpanelRight = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelNewPassword = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonChangePassword = new javax.swing.JButton();
        jPasswordFieldConNewPassword = new javax.swing.JPasswordField();
        jLabelConPassword = new javax.swing.JLabel();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 67, 143));

        jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLogin.setPreferredSize(new java.awt.Dimension(900, 550));

        jpanelLeft.setBackground(new java.awt.Color(26, 67, 143));
        jpanelLeft.setPreferredSize(new java.awt.Dimension(450, 550));

        jButtonBack.setBackground(new java.awt.Color(26, 67, 143));
        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBack.setText("<");
        jButtonBack.setAlignmentY(0.0F);
        jButtonBack.setBorder(null);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.setFocusable(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelLeftLayout = new javax.swing.GroupLayout(jpanelLeft);
        jpanelLeft.setLayout(jpanelLeftLayout);
        jpanelLeftLayout.setHorizontalGroup(
            jpanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(418, Short.MAX_VALUE))
        );
        jpanelLeftLayout.setVerticalGroup(
            jpanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        jpanelRight.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRight.setPreferredSize(new java.awt.Dimension(450, 550));

        jLabelLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(26, 67, 143));
        jLabelLogin.setText("Forgot Password");

        jLabelNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNewPassword.setText("New Password");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUsername.setText("Username");

        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jButtonChangePassword.setBackground(new java.awt.Color(26, 67, 143));
        jButtonChangePassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        jButtonChangePassword.setText("Change Password");
        jButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswordActionPerformed(evt);
            }
        });

        jPasswordFieldConNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConNewPasswordActionPerformed(evt);
            }
        });

        jLabelConPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelConPassword.setText("Confirm Password");

        jPasswordFieldNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldNewPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRightLayout = new javax.swing.GroupLayout(jpanelRight);
        jpanelRight.setLayout(jpanelRightLayout);
        jpanelRightLayout.setHorizontalGroup(
            jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRightLayout.createSequentialGroup()
                .addGroup(jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRightLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabelLogin))
                    .addGroup(jpanelRightLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordFieldNewPassword)
                            .addComponent(jLabelConPassword)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jLabelUsername)
                            .addComponent(jLabelNewPassword)
                            .addComponent(jPasswordFieldConNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addGroup(jpanelRightLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButtonChangePassword)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jpanelRightLayout.setVerticalGroup(
            jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRightLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelLogin)
                .addGap(45, 45, 45)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNewPassword)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelConPassword)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldConNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addComponent(jpanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void jPasswordFieldConNewPasswordActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		
	}

	protected void jTextFieldUsernameActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		
	}

	private void jButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswordActionPerformed
		if("".equals(jTextFieldUsername.getText()) ||  "".equals(new String(jPasswordFieldNewPassword.getPassword())) || "".equals(new String(jPasswordFieldConNewPassword.getPassword()))) {
        	JOptionPane.showMessageDialog(null, "Fill the all Fields", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        else if(!new String(jPasswordFieldNewPassword.getPassword()).equals(new String(jPasswordFieldConNewPassword.getPassword()))) {
        	JOptionPane.showMessageDialog(null, "Passwords are not match", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        else {
        	String username = jTextFieldUsername.getText();
        	String password = new String(jPasswordFieldNewPassword.getPassword());
        	
        	boolean isTrue;
        	isTrue = user.updatePassword(username, password);
        	
        	if(isTrue) {
        		JOptionPane.showMessageDialog(null, "Password changed.", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        		loginInterface loginFrame = new loginInterface();
            	loginFrame.setResizable(false);
        		loginFrame.setVisible(true);
        		loginFrame.setLocationRelativeTo(null);
        		this.dispose();
        	}
        }
    }//GEN-LAST:event_jButtonChangePasswordActionPerformed

    private void jPasswordFieldNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldNewPasswordActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
    	loginInterface loginFrame = new loginInterface();
    	loginFrame.setResizable(false);
		loginFrame.setVisible(true);
		loginFrame.setLocationRelativeTo(null);
		this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                forgotPassword forgotPassworFrame = new forgotPassword();
                forgotPassworFrame.pack();
                forgotPassworFrame.setLocationRelativeTo(null);
                forgotPassworFrame.setResizable(false);
                forgotPassworFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonChangePassword;
    private javax.swing.JLabel jLabelConPassword;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNewPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldConNewPassword;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JPanel jpanelLeft;
    private javax.swing.JPanel jpanelRight;
    // End of variables declaration//GEN-END:variables
}
