/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginPackage;

import javax.swing.JOptionPane;


/**
 *
 * @author nidul
 */
public class loginInterface extends javax.swing.JFrame {

    /**
     * Creates new form loginInterface
     */
    public loginInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jpanelLeft = new javax.swing.JPanel();
        jpanelRight = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonSignup = new javax.swing.JButton();
        jLabelSignup = new javax.swing.JLabel();
        jButtonForgotPassword = new javax.swing.JButton();
        jPasswordFieldLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(26, 67, 143));

        jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLogin.setPreferredSize(new java.awt.Dimension(900, 550));

        jpanelLeft.setBackground(new java.awt.Color(26, 67, 143));
        jpanelLeft.setPreferredSize(new java.awt.Dimension(450, 550));

        javax.swing.GroupLayout jpanelLeftLayout = new javax.swing.GroupLayout(jpanelLeft);
        jpanelLeft.setLayout(jpanelLeftLayout);
        jpanelLeftLayout.setHorizontalGroup(
            jpanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jpanelLeftLayout.setVerticalGroup(
            jpanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jpanelRight.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRight.setPreferredSize(new java.awt.Dimension(450, 550));

        jLabelLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(26, 67, 143));
        jLabelLogin.setText("LOGIN");

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPassword.setText("Password");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelUsername.setText("Username");

        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButtonLogin.setBackground(new java.awt.Color(26, 67, 143));
        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonSignup.setBackground(new java.awt.Color(26, 67, 143));
        jButtonSignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSignup.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSignup.setText("SignUp");
        jButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignupActionPerformed(evt);
            }
        });

        jLabelSignup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSignup.setText("Don't have an account?");

        jButtonForgotPassword.setForeground(new java.awt.Color(26, 67, 143));
        jButtonForgotPassword.setText("Forgot Password");
        jButtonForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForgotPasswordActionPerformed(evt);
            }
        });

        jPasswordFieldLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jpanelRightLayout = new javax.swing.GroupLayout(jpanelRight);
        jpanelRight.setLayout(jpanelRightLayout);
        jpanelRightLayout.setHorizontalGroup(
            jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRightLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRightLayout.createSequentialGroup()
                        .addComponent(jLabelLogin)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRightLayout.createSequentialGroup()
                        .addGroup(jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonForgotPassword)
                            .addGroup(jpanelRightLayout.createSequentialGroup()
                                .addComponent(jLabelSignup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSignup))
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jLabelUsername)
                            .addComponent(jButtonLogin)
                            .addComponent(jLabelPassword)
                            .addComponent(jPasswordFieldLogin))
                        .addGap(51, 51, 51))))
        );
        jpanelRightLayout.setVerticalGroup(
            jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRightLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelLogin)
                .addGap(47, 47, 47)
                .addComponent(jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonForgotPassword)
                .addGap(29, 29, 29)
                .addComponent(jButtonLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSignup)
                    .addComponent(jButtonSignup))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addComponent(jpanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        if("".equals(jTextFieldUsername.getText()) || "".equals(new String(jPasswordFieldLogin.getPassword()))) {
        	JOptionPane.showMessageDialog(null, "Fill the all Fields", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        else {
        	String username = jTextFieldUsername.getText();
            String password = new String(jPasswordFieldLogin.getPassword());
            if(user.validate(username, password)) {
            	userProfile userProfileFrame = new userProfile();
            	userProfileFrame.pack();
            	userProfileFrame.setLocationRelativeTo(null);
            	userProfileFrame.setResizable(false);
            	userProfileFrame.setVisible(true);
            	this.dispose();
            	 
            }
            else {
            	JOptionPane.showMessageDialog(null, "Username or Password is incorrect", "Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignupActionPerformed
        // Open register interface and close login interface
        registerInterface registerFrame = new registerInterface();
        registerFrame.setResizable(false);
        registerFrame.setVisible(true);
        registerFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonSignupActionPerformed

    private void jButtonForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForgotPasswordActionPerformed
    	forgotPassword forgotPassworFrame = new forgotPassword();
    	forgotPassworFrame.setResizable(false);
    	forgotPassworFrame.setVisible(true);
    	forgotPassworFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtonForgotPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 

        /* Create and display the  form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                loginInterface loginFrame = new loginInterface();
                loginFrame.pack();
                loginFrame.setLocationRelativeTo(null);
                loginFrame.setResizable(false);
                loginFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonForgotPassword;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSignup;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSignup;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JPanel jpanelLeft;
    private javax.swing.JPanel jpanelRight;
    // End of variables declaration//GEN-END:variables
}
